// Mocks generated by Mockito 5.4.6 from annotations
// in gaming_library_assessment_flutter/test/cubit/game_detail/game_detail_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:gaming_library_assessment_flutter/core/data/models/error.dart'
    as _i5;
import 'package:gaming_library_assessment_flutter/features/game_detail/data/models/game_detail_response.dart'
    as _i6;
import 'package:gaming_library_assessment_flutter/features/game_detail/domain/repository/game_detail_repository.dart'
    as _i3;
import 'package:gaming_library_assessment_flutter/features/tracker/data/models/saved_game.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GameDetailRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameDetailRepository extends _i1.Mock
    implements _i3.GameDetailRepository {
  MockGameDetailRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ErrorType, _i6.GameDetailResponse>> fetchGameDetail(
          {required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchGameDetail,
          [],
          {#id: id},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.ErrorType, _i6.GameDetailResponse>>.value(
                _FakeEither_0<_i5.ErrorType, _i6.GameDetailResponse>(
          this,
          Invocation.method(
            #fetchGameDetail,
            [],
            {#id: id},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.ErrorType, _i6.GameDetailResponse>>);

  @override
  _i4.Future<void> saveGame({required _i7.SavedGame? game}) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveGame,
          [],
          {#game: game},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unsaveGame({required int? id}) => (super.noSuchMethod(
        Invocation.method(
          #unsaveGame,
          [],
          {#id: id},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i7.SavedGame?> getSavedGame({required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSavedGame,
          [],
          {#id: id},
        ),
        returnValue: _i4.Future<_i7.SavedGame?>.value(),
      ) as _i4.Future<_i7.SavedGame?>);
}
