include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    lines_longer_than_80_chars: true
    avoid_empty_else: true
    prefer_null_aware_operators: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_foreach: true
    avoid_unnecessary_containers: false
