include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_single_quotes
    - require_trailing_commas
    - lines_longer_than_80_chars
    - avoid_empty_else
    - prefer_null_aware_operators
    - prefer_if_elements_to_conditional_expressions
    - prefer_foreach
    - avoid_unnecessary_containers
    - await_only_futures
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_returning_null_for_void
    - camel_case_extensions
    - camel_case_types
    - no_default_cases
    - no_duplicate_case_values
    - prefer_function_declarations_over_variables
