name: gaming_library_assessment_flutter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

isar_version: &isar_version ^3.1.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # intl Localization
  intl: any
  flutter_localizations:
    sdk: flutter

  # Routes
  go_router: ^15.1.2

  # Shared pref
  shared_preferences: ^2.5.3

  # Bloc
  flutter_bloc: ^9.1.1

  # Bloc Transformer
  bloc_concurrency: ^0.3.0

  # Dio
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  http_parser: ^4.1.2
  retrofit: ^4.4.2

  # Local db
  isar:
    version: *isar_version
    hosted: https://pub.isar-community.dev/

  isar_flutter_libs:
    version: *isar_version
    hosted: https://pub.isar-community.dev/

  # Either - Left or Right
  dartz: ^0.10.1

  # Json
  json_annotation: ^4.9.0

  # DI
  get_it: ^8.0.3
  injectable: ^2.5.0
  injectable_generator: ^2.1.6

  # Equate
  equatable: ^2.0.7

  # UUID
  uuid: ^4.5.1

  # Lottie
  lottie: ^3.3.1
  # Flutter animation
  flutter_animate: ^4.5.2

  # Slidable
  flutter_slidable: ^4.0.0

  # Text scaler
  auto_size_text: ^3.0.0
  readmore: ^3.0.0

  # Shimmer loading
  skeletonizer: ^2.0.1

  scroll_snap_list: ^0.9.1
  scrollable_positioned_list: ^0.3.8

  # Network image
  cached_network_image: ^3.3.1

  # Font
  google_fonts: 6.1.0

  # Envied - Privatise file
  envied: ^0.5.3

  # Path provider
  path_provider: ^2.1.2

  # Mocking
  mockito: ^5.4.4
  http_mock_adapter: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  # Json
  json_serializable: ^6.9.0

  # Code generator
  build_runner: ^2.4.15

  # Testing
  bloc_test: ^10.0.0

  # Envied generator
  envied_generator: ^0.5.3

  # Retrofit generator
  retrofit_generator: ^9.2.0

  # Isar generator
  isar_generator:
    version: *isar_version
    hosted: https://pub.isar-community.dev/


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
