// Mocks generated by Mockito 5.4.6 from annotations
// in gaming_library_assessment_flutter/test/cubit/game_screenshot/game_screenshot_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:gaming_library_assessment_flutter/core/data/models/result.dart'
    as _i4;
import 'package:gaming_library_assessment_flutter/features/game_detail/data/models/screenshot_response.dart'
    as _i5;
import 'package:gaming_library_assessment_flutter/features/game_detail/domain/repositories/game_screenshots_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GameScreenshotsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameScreenshotsRepository extends _i1.Mock
    implements _i2.GameScreenshotsRepository {
  MockGameScreenshotsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.ScreenshotResponse>> fetchGameScreenshots(
          {required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchGameScreenshots,
          [],
          {#id: id},
        ),
        returnValue: _i3.Future<_i4.Result<_i5.ScreenshotResponse>>.value(
            _i6.dummyValue<_i4.Result<_i5.ScreenshotResponse>>(
          this,
          Invocation.method(
            #fetchGameScreenshots,
            [],
            {#id: id},
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.ScreenshotResponse>>);
}
