// Mocks generated by Mockito 5.4.6 from annotations
// in gaming_library_assessment_flutter/test/repository/games/games_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:gaming_library_assessment_flutter/core/data/models/games_model.dart'
    as _i5;
import 'package:gaming_library_assessment_flutter/features/games/data/datasources/games_datasource.dart'
    as _i3;
import 'package:gaming_library_assessment_flutter/features/games/services/igdb_api_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeIgdbApiService_0 extends _i1.SmartFake
    implements _i2.IgdbApiService {
  _FakeIgdbApiService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GamesDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGamesDataSource extends _i1.Mock implements _i3.GamesDataSource {
  MockGamesDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IgdbApiService get igdbApiService => (super.noSuchMethod(
        Invocation.getter(#igdbApiService),
        returnValue: _FakeIgdbApiService_0(
          this,
          Invocation.getter(#igdbApiService),
        ),
      ) as _i2.IgdbApiService);

  @override
  _i4.Future<_i5.GamesModel> fetchDatasourceGames({
    int? page = 1,
    int? pageSize = 20,
    String? searchTerm,
    String? dateRange,
    String? orderings,
    String? platforms,
    String? genres,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDatasourceGames,
          [],
          {
            #page: page,
            #pageSize: pageSize,
            #searchTerm: searchTerm,
            #dateRange: dateRange,
            #orderings: orderings,
            #platforms: platforms,
            #genres: genres,
          },
        ),
        returnValue:
            _i4.Future<_i5.GamesModel>.value(_i6.dummyValue<_i5.GamesModel>(
          this,
          Invocation.method(
            #fetchDatasourceGames,
            [],
            {
              #page: page,
              #pageSize: pageSize,
              #searchTerm: searchTerm,
              #dateRange: dateRange,
              #orderings: orderings,
              #platforms: platforms,
              #genres: genres,
            },
          ),
        )),
      ) as _i4.Future<_i5.GamesModel>);
}
