// Mocks generated by Mockito 5.4.6 from annotations
// in gaming_library_assessment_flutter/test/repository/featured/featured_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:gaming_library_assessment_flutter/core/data/models/game.dart'
    as _i7;
import 'package:gaming_library_assessment_flutter/features/featured/data/datasources/featured_local_datasource.dart'
    as _i2;
import 'package:gaming_library_assessment_flutter/features/featured/domain/repositories/featured_repository.dart'
    as _i5;
import 'package:gaming_library_assessment_flutter/features/featured/services/featured_api_service.dart'
    as _i6;
import 'package:gaming_library_assessment_flutter/features/tracker/data/models/saved_game.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FeaturedLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeaturedLocalDatasource extends _i1.Mock
    implements _i2.FeaturedLocalDatasource {
  MockFeaturedLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> countSavedGames() =>
      (super.noSuchMethod(
            Invocation.method(#countSavedGames, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<Set<int>> getOwnedGameIds() =>
      (super.noSuchMethod(
            Invocation.method(#getOwnedGameIds, []),
            returnValue: _i3.Future<Set<int>>.value(<int>{}),
          )
          as _i3.Future<Set<int>>);

  @override
  _i3.Future<List<_i4.SavedGame>> getWishlistedGames() =>
      (super.noSuchMethod(
            Invocation.method(#getWishlistedGames, []),
            returnValue: _i3.Future<List<_i4.SavedGame>>.value(
              <_i4.SavedGame>[],
            ),
          )
          as _i3.Future<List<_i4.SavedGame>>);

  @override
  _i3.Future<List<_i4.SavedGame>> getNowPlayingGames() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingGames, []),
            returnValue: _i3.Future<List<_i4.SavedGame>>.value(
              <_i4.SavedGame>[],
            ),
          )
          as _i3.Future<List<_i4.SavedGame>>);

  @override
  _i3.Future<double> getThisWeekPlayHours() =>
      (super.noSuchMethod(
            Invocation.method(#getThisWeekPlayHours, []),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<void> saveGenrePreferences(List<int>? genreIds, bool? isSkipped) =>
      (super.noSuchMethod(
            Invocation.method(#saveGenrePreferences, [genreIds, isSkipped]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i5.GenrePreferencesEntity?> getSavedGenrePreferences() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedGenrePreferences, []),
            returnValue: _i3.Future<_i5.GenrePreferencesEntity?>.value(),
          )
          as _i3.Future<_i5.GenrePreferencesEntity?>);

  @override
  _i3.Future<List<_i4.SavedGame?>> getSavedGames() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedGames, []),
            returnValue: _i3.Future<List<_i4.SavedGame?>>.value(
              <_i4.SavedGame?>[],
            ),
          )
          as _i3.Future<List<_i4.SavedGame?>>);
}

/// A class which mocks [FeaturedApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeaturedApiService extends _i1.Mock
    implements _i6.FeaturedApiService {
  MockFeaturedApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i7.Game>> fetchGames(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#fetchGames, [query]),
            returnValue: _i3.Future<List<_i7.Game>>.value(<_i7.Game>[]),
          )
          as _i3.Future<List<_i7.Game>>);
}
