// Mocks generated by Mockito 5.4.6 from annotations
// in gaming_library_assessment_flutter/test/cubit/tracker/tracker_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:gaming_library_assessment_flutter/core/domain/entities/tracker_saved_game_entity.dart'
    as _i4;
import 'package:gaming_library_assessment_flutter/core/enums/saved_game_filter_tag.dart'
    as _i5;
import 'package:gaming_library_assessment_flutter/features/tracker/domain/repositories/tracker_repository.dart'
    as _i2;
import 'package:gaming_library_assessment_flutter/features/tracker/domain/use_cases/get_tracker_sort_use_case.dart'
    as _i6;
import 'package:gaming_library_assessment_flutter/features/tracker/domain/use_cases/save_tracker_sort_use_case.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TrackerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrackerRepository extends _i1.Mock implements _i2.TrackerRepository {
  MockTrackerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TrackerSavedGameEntity>> getSavedGames() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSavedGames,
          [],
        ),
        returnValue: _i3.Future<List<_i4.TrackerSavedGameEntity>>.value(
            <_i4.TrackerSavedGameEntity>[]),
      ) as _i3.Future<List<_i4.TrackerSavedGameEntity>>);

  @override
  _i3.Stream<List<_i4.TrackerSavedGameEntity>> savedGamesStream(
    _i5.SavedGameFilterTag? tag,
    String? searchTerm,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #savedGamesStream,
          [
            tag,
            searchTerm,
          ],
        ),
        returnValue: _i3.Stream<List<_i4.TrackerSavedGameEntity>>.empty(),
      ) as _i3.Stream<List<_i4.TrackerSavedGameEntity>>);

  @override
  _i3.Stream<List<_i4.TrackerSavedGameEntity>> searchGamesStream(
          String? term) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchGamesStream,
          [term],
        ),
        returnValue: _i3.Stream<List<_i4.TrackerSavedGameEntity>>.empty(),
      ) as _i3.Stream<List<_i4.TrackerSavedGameEntity>>);

  @override
  _i3.Future<void> removeSavedGame(int? id) => (super.noSuchMethod(
        Invocation.method(
          #removeSavedGame,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [GetTrackerSortUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTrackerSortUseCase extends _i1.Mock
    implements _i6.GetTrackerSortUseCase {
  MockGetTrackerSortUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.SavedGameFilterTag call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.SavedGameFilterTag.recentlyChanged,
      ) as _i5.SavedGameFilterTag);
}

/// A class which mocks [SaveTrackerSortUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveTrackerSortUseCase extends _i1.Mock
    implements _i7.SaveTrackerSortUseCase {
  MockSaveTrackerSortUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> call(_i5.SavedGameFilterTag? tag) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [tag],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
