// Mocks generated by Mockito 5.4.4 from annotations
// in gaming_library_assessment_flutter/test/cubit/most_anticipated/most_anticipated_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:gaming_library_assessment_flutter/data/models/error.dart'
    as _i5;
import 'package:gaming_library_assessment_flutter/features/featured/domain/repository/featured_repository.dart'
    as _i3;
import 'package:gaming_library_assessment_flutter/features/games/data/models/games_response.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FeaturedRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeaturedRepository extends _i1.Mock
    implements _i3.FeaturedRepository {
  MockFeaturedRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.ErrorType, _i6.GamesResponse>>
      fetchMostAnticipated() => (super.noSuchMethod(
            Invocation.method(
              #fetchMostAnticipated,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.ErrorType, _i6.GamesResponse>>.value(
                    _FakeEither_0<_i5.ErrorType, _i6.GamesResponse>(
              this,
              Invocation.method(
                #fetchMostAnticipated,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.ErrorType, _i6.GamesResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.ErrorType, _i6.GamesResponse>>
      fetchBestMetacritic() => (super.noSuchMethod(
            Invocation.method(
              #fetchBestMetacritic,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.ErrorType, _i6.GamesResponse>>.value(
                    _FakeEither_0<_i5.ErrorType, _i6.GamesResponse>(
              this,
              Invocation.method(
                #fetchBestMetacritic,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.ErrorType, _i6.GamesResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.ErrorType, _i6.GamesResponse>>
      fetchLatestReleases() => (super.noSuchMethod(
            Invocation.method(
              #fetchLatestReleases,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.ErrorType, _i6.GamesResponse>>.value(
                    _FakeEither_0<_i5.ErrorType, _i6.GamesResponse>(
              this,
              Invocation.method(
                #fetchLatestReleases,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.ErrorType, _i6.GamesResponse>>);
}
