// Mocks generated by Mockito 5.4.6 from annotations
// in gaming_library_assessment_flutter/test/cubit/games/games_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:gaming_library_assessment_flutter/core/data/models/result.dart'
    as _i4;
import 'package:gaming_library_assessment_flutter/core/domain/entities/game_list_entity.dart'
    as _i5;
import 'package:gaming_library_assessment_flutter/core/enums/game_genre.dart'
    as _i7;
import 'package:gaming_library_assessment_flutter/core/enums/game_ordering.dart'
    as _i8;
import 'package:gaming_library_assessment_flutter/features/filter/data/models/games_platform.dart'
    as _i6;
import 'package:gaming_library_assessment_flutter/features/games/domain/use_cases/fetch_games_use_case.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FetchGamesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchGamesUseCase extends _i1.Mock implements _i2.FetchGamesUseCase {
  MockFetchGamesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.GameListEntity>> call({
    required int? page,
    String? searchTerm,
    DateTime? dateFrom,
    DateTime? dateTo,
    Set<_i6.GamePlatform>? platforms,
    Set<_i7.GameGenre>? genres,
    _i8.GameOrdering? ordering,
    bool? ascending = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #page: page,
              #searchTerm: searchTerm,
              #dateFrom: dateFrom,
              #dateTo: dateTo,
              #platforms: platforms,
              #genres: genres,
              #ordering: ordering,
              #ascending: ascending,
            }),
            returnValue: _i3.Future<_i4.Result<_i5.GameListEntity>>.value(
              _i9.dummyValue<_i4.Result<_i5.GameListEntity>>(
                this,
                Invocation.method(#call, [], {
                  #page: page,
                  #searchTerm: searchTerm,
                  #dateFrom: dateFrom,
                  #dateTo: dateTo,
                  #platforms: platforms,
                  #genres: genres,
                  #ordering: ordering,
                  #ascending: ascending,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.GameListEntity>>);
}
