// Mocks generated by Mockito 5.4.4 from annotations
// in gaming_library_assessment_flutter/test/repository/tracker/tracker_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:gaming_library_assessment_flutter/core/enums/saved_game_filter_tag.dart'
    as _i5;
import 'package:gaming_library_assessment_flutter/features/tracker/data/datasources/local/game_local_datasource.dart'
    as _i2;
import 'package:gaming_library_assessment_flutter/features/tracker/data/models/saved_game.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GameLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameLocalDatasource extends _i1.Mock
    implements _i2.GameLocalDatasource {
  MockGameLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveGame({required _i4.SavedGame? game}) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveGame,
          [],
          {#game: game},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> unsaveGame({required int? id}) => (super.noSuchMethod(
        Invocation.method(
          #unsaveGame,
          [],
          {#id: id},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.SavedGame?> getSavedGame({required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSavedGame,
          [],
          {#id: id},
        ),
        returnValue: _i3.Future<_i4.SavedGame?>.value(),
      ) as _i3.Future<_i4.SavedGame?>);

  @override
  _i3.Future<List<_i4.SavedGame?>> getSavedGames() => (super.noSuchMethod(
        Invocation.method(
          #getSavedGames,
          [],
        ),
        returnValue: _i3.Future<List<_i4.SavedGame?>>.value(<_i4.SavedGame?>[]),
      ) as _i3.Future<List<_i4.SavedGame?>>);

  @override
  _i3.Stream<List<_i4.SavedGame>> listenToSavedGames(
          _i5.SavedGameFilterTag? tag) =>
      (super.noSuchMethod(
        Invocation.method(
          #listenToSavedGames,
          [tag],
        ),
        returnValue: _i3.Stream<List<_i4.SavedGame>>.empty(),
      ) as _i3.Stream<List<_i4.SavedGame>>);
}
